In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [3]:
from ucimlrepo import fetch_ucirepo 

heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features  
y = heart_disease.data.targets   

data = X.copy()
data['Diagnosis'] = y  

print("Dataset Shape:", data.shape)
print("Columns:", data.columns)

data.to_csv("../data/raw/raw_heart_disease_data.csv", index=False)

Dataset Shape: (303, 14)
Columns: Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'Diagnosis'],
      dtype='object')


In [4]:
df = pd.read_csv("../data/raw/raw_heart_disease_data.csv")

df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  Diagnosis  
0        3  0.0   6.0          0  
1        2  3.0   3.0          2  
2        2  2.0   7.0          1  
3        3  0.0   3.0          0  
4        1  0.0   3.0          0  
..     ...  ...   ...        ...  
298      2  0.0   7.0          1  
299      2  2.0   7.0          2  
300      2  1.0   7.0          3  
301      2  1.0   3.0          1  
302      1  NaN   3.0          0  

[303 rows x 14 columns]

In [5]:
new_column_names = ["age", "sex", "chest_pain_type", "resting_blood_pressure", "cholesterol", "fasting_blood_sugar", 
                "rest_ecg", "max_heart_rate", "exercise_induced_angina", "st_depression", "slope", 
               "num_of_vessels", "thalassemia", "diagnosis"]


df.columns = new_column_names

In [6]:
df

age  sex  chest_pain_type  resting_blood_pressure  cholesterol  \
0     63    1                1                     145          233   
1     67    1                4                     160          286   
2     67    1                4                     120          229   
3     37    1                3                     130          250   
4     41    0                2                     130          204   
..   ...  ...              ...                     ...          ...   
298   45    1                1                     110          264   
299   68    1                4                     144          193   
300   57    1                4                     130          131   
301   57    0                2                     130          236   
302   38    1                3                     138          175   

     fasting_blood_sugar  rest_ecg  max_heart_rate  exercise_induced_angina  \
0                      1         2             150                        0   
1                      0         2             108                        1   
2                      0         2             129                        1   
3                      0         0             187                        0   
4                      0         2             172                        0   
..                   ...       ...             ...                      ...   
298                    0         0             132                        0   
299                    1         0             141                        0   
300                    0         0             115                        1   
301                    0         2             174                        0   
302                    0         0             173                        0   

     st_depression  slope  num_of_vessels  thalassemia  diagnosis  
0              2.3      3             0.0          6.0          0  
1              1.5      2             3.0          3.0          2  
2              2.6      2             2.0          7.0          1  
3              3.5      3             0.0          3.0          0  
4              1.4      1             0.0          3.0          0  
..             ...    ...             ...          ...        ...  
298            1.2      2             0.0          7.0          1  
299            3.4      2             2.0          7.0          2  
300            1.2      2             1.0          7.0          3  
301            0.0      2             1.0          3.0          1  
302            0.0      1             NaN          3.0          0  

[303 rows x 14 columns]

In [7]:
df.dtypes

age                          int64
sex                          int64
chest_pain_type              int64
resting_blood_pressure       int64
cholesterol                  int64
fasting_blood_sugar          int64
rest_ecg                     int64
max_heart_rate               int64
exercise_induced_angina      int64
st_depression              float64
slope                        int64
num_of_vessels             float64
thalassemia                float64
diagnosis                    int64
dtype: object

In [8]:
df['diagnosis'].unique()

array([0, 2, 1, 3, 4])

In [9]:
df['sex'].unique()

array([1, 0])

In [10]:
df['chest_pain_type'].unique()

array([1, 4, 3, 2])

In [11]:
df['fasting_blood_sugar'].unique()

array([1, 0])

In [12]:
df['rest_ecg'].unique()

array([2, 0, 1])

In [13]:
df['thalassemia'].unique()

array([ 6.,  3.,  7., nan])

In [14]:
df.loc[(df['chest_pain_type'] == 1), 'chest_pain_type'] = 'typical angina'
df.loc[(df['chest_pain_type'] == 2), 'chest_pain_type'] = 'atypical angina'
df.loc[(df['chest_pain_type'] == 3), 'chest_pain_type'] = 'non-anginal pain'
df.loc[(df['chest_pain_type'] == 4), 'chest_pain_type'] = 'asymptomatic'

/var/folders/8t/5wsb53gx291_v2jk3nfmym880000gn/T/ipykernel_89511/1121403262.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'typical angina' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['chest_pain_type'] == 1), 'chest_pain_type'] = 'typical angina'


In [15]:
df.loc[(df['fasting_blood_sugar'] == 'yes'), 'fasting_blood_sugar'] = 1
df.loc[(df['fasting_blood_sugar'] == 'no'), 'fasting_blood_sugar'] = 0

In [16]:
df.loc[(df['rest_ecg'] == 0), 'rest_ecg'] = 'normal'
df.loc[(df['rest_ecg'] == 1), 'rest_ecg'] = 'ST-T wave abnormality'
df.loc[(df['rest_ecg'] == 2), 'rest_ecg'] = 'left ventricular hypertrophy'


/var/folders/8t/5wsb53gx291_v2jk3nfmym880000gn/T/ipykernel_89511/838408438.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'normal' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['rest_ecg'] == 0), 'rest_ecg'] = 'normal'


In [17]:
df.loc[(df['exercise_induced_angina'] == 0), 'exercise_induced_angina'] = 'no'
df.loc[(df['exercise_induced_angina'] == 1), 'exercise_induced_angina'] = 'yes'

/var/folders/8t/5wsb53gx291_v2jk3nfmym880000gn/T/ipykernel_89511/360885403.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'no' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['exercise_induced_angina'] == 0), 'exercise_induced_angina'] = 'no'


In [18]:
df.loc[(df['slope'] == 1), 'slope'] = 'upsloping'
df.loc[(df['slope'] == 2), 'slope'] = 'flat'
df.loc[(df['slope'] == 3), 'slope'] = 'downsloping'

/var/folders/8t/5wsb53gx291_v2jk3nfmym880000gn/T/ipykernel_89511/1810071572.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'upsloping' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['slope'] == 1), 'slope'] = 'upsloping'


In [19]:
df.loc[(df['thalassemia'] == 3.), 'thalassemia'] = 'normal'
df.loc[(df['thalassemia'] == 6.), 'thalassemia'] = 'fixed defect'
df.loc[(df['thalassemia'] == 7.), 'thalassemia'] = 'reversable defect'

/var/folders/8t/5wsb53gx291_v2jk3nfmym880000gn/T/ipykernel_89511/2175494109.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'normal' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[(df['thalassemia'] == 3.), 'thalassemia'] = 'normal'


In [20]:
df.loc[(df['diagnosis'] == 2), 'diagnosis'] = 1
df.loc[(df['diagnosis'] == 3), 'diagnosis'] = 1
df.loc[(df['diagnosis'] == 4), 'diagnosis'] = 1

In [21]:
df

age  sex   chest_pain_type  resting_blood_pressure  cholesterol  \
0     63    1    typical angina                     145          233   
1     67    1      asymptomatic                     160          286   
2     67    1      asymptomatic                     120          229   
3     37    1  non-anginal pain                     130          250   
4     41    0   atypical angina                     130          204   
..   ...  ...               ...                     ...          ...   
298   45    1    typical angina                     110          264   
299   68    1      asymptomatic                     144          193   
300   57    1      asymptomatic                     130          131   
301   57    0   atypical angina                     130          236   
302   38    1  non-anginal pain                     138          175   

     fasting_blood_sugar                      rest_ecg  max_heart_rate  \
0                      1  left ventricular hypertrophy             150   
1                      0  left ventricular hypertrophy             108   
2                      0  left ventricular hypertrophy             129   
3                      0                        normal             187   
4                      0  left ventricular hypertrophy             172   
..                   ...                           ...             ...   
298                    0                        normal             132   
299                    1                        normal             141   
300                    0                        normal             115   
301                    0  left ventricular hypertrophy             174   
302                    0                        normal             173   

    exercise_induced_angina  st_depression        slope  num_of_vessels  \
0                        no            2.3  downsloping             0.0   
1                       yes            1.5         flat             3.0   
2                       yes            2.6         flat             2.0   
3                        no            3.5  downsloping             0.0   
4                        no            1.4    upsloping             0.0   
..                      ...            ...          ...             ...   
298                      no            1.2         flat             0.0   
299                      no            3.4         flat             2.0   
300                     yes            1.2         flat             1.0   
301                      no            0.0         flat             1.0   
302                      no            0.0    upsloping             NaN   

           thalassemia  diagnosis  
0         fixed defect          0  
1               normal          1  
2    reversable defect          1  
3               normal          0  
4               normal          0  
..                 ...        ...  
298  reversable defect          1  
299  reversable defect          1  
300  reversable defect          1  
301             normal          1  
302             normal          0  

[303 rows x 14 columns]

In [22]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
rest_ecg                   0
max_heart_rate             0
exercise_induced_angina    0
st_depression              0
slope                      0
num_of_vessels             4
thalassemia                2
diagnosis                  0
dtype: int64

In [23]:
df = df.dropna()

In [24]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
rest_ecg                   0
max_heart_rate             0
exercise_induced_angina    0
st_depression              0
slope                      0
num_of_vessels             0
thalassemia                0
diagnosis                  0
dtype: int64

In [25]:
df.to_csv("../data/processed/processed_heart_disease_data.csv", index=False)